In [1]:
# Fox News Test
#https://stackoverflow.com/questions/75794919/how-to-segment-and-transcribe-an-audio-from-a-video-into-timestamped-segments

#Fox News Youtube Channel
#https://www.youtube.com/@FoxNews/streams

#Open Ai Transcriber
#https://github.com/openai/whisper

#Getting Youtube video from channel
#https://stackoverflow.com/questions/67456975/cant-get-youtube-video-urls-using-beautifulsoup

In [2]:
import urllib3.request,sys,time

In [3]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

In [4]:
import requests

In [5]:
import pandas as pd

In [6]:
import numpy as np

In [7]:
import re
import mock

from pytube.cipher import get_throttling_function_code

#https://github.com/juanbindez/pytubefix
from pytubefix import YouTube
from pytubefix.cli import on_progress

In [8]:
import whisper

In [ ]:
#import ffmpeg

In [9]:
###############################################################################################################

In [10]:
#Step 1: Get the 
#options=Options()
#options.add_argument("start-maximized")
#path to chrome driver
#driver = webdriver.Chrome(options=options)
#url='https://www.youtube.com/@FoxNews/streams'
#driver.get(url)
#driver

In [11]:
#https://www.selenium.dev/documentation/webdriver/elements/finders/
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.common.exceptions import TimeoutException
options=Options()
options.add_argument("start-maximized")
#path to chrome driver
driver = webdriver.Chrome(options=options)
try: 
    driver.set_page_load_timeout(60)
    driver.get('https://www.youtube.com/@FoxNews/streams')
    element=driver.find_elements(By.XPATH,'//*[@href]')
    for e in element:
        print(e.get_attribute('href'))
except TimeoutException:
    isrunning = 0
    print("Exception has been thrown. ")
    driver.close()

https://www.youtube.com/s/desktop/70f744c3/img/logos/favicon.ico
https://www.youtube.com/s/desktop/70f744c3/img/logos/favicon_32x32.png
https://www.youtube.com/s/desktop/70f744c3/img/logos/favicon_48x48.png
https://www.youtube.com/s/desktop/70f744c3/img/logos/favicon_96x96.png
https://www.youtube.com/s/desktop/70f744c3/img/logos/favicon_144x144.png
https://i.ytimg.com/generate_204
https://www.youtube.com/s/_/ytmainappweb/_/js/k=ytmainappweb.kevlar_base.en_US.4r1Lpqkq5-8.es5.O/d=0/br=1/rs=AGKMywGT1jDt4a4jMqwioTgsQXIQX66ADQ
https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&family=YouTube+Sans:wght@300..900&display=swap
https://www.youtube.com/s/desktop/70f744c3/cssbin/www-onepick.css
https://www.youtube.com/s/_/ytmainappweb/_/ss/k=ytmainappweb.kevlar_base.9Lsn3BCm2ac.L.B1.O/am=AAAQKA/d=0/br=1/rs=AGKMywHupyPI5O2AdzHJR5vWcHk3G6Dt1A
https://www.youtube.com/opensearch?locale=en_US
https://www.youtube.com/manifest.webmanifest
https://www.youtube.com/channel/UCXIJgqnII2ZOINSWNOGFThA
https://m.youtube.com/@FoxNews/streams
https://m.youtube.com/@FoxNews/streams
https://www.youtube.com/feeds/videos.xml?channel_id=UCXIJgqnII2ZOINSWNOGFThA
https://yt3.googleusercontent.com/G3gLy3HBgiZ21mEt1uzR0VPA6VXpsgJReuD7Z91nHwcgyFVu_QpHNpxuULN1D0YEQBwD0F1HwQ=s900-c-k-c0x00ffffff-no-rj
https://www.youtube.com/channel/UCXIJgqnII2ZOINSWNOGFThA
https://fonts.googleapis.com/css?family=Roboto:300italic,400italic,500italic,700italic
https://fonts.googleapis.com/css?family=Roboto+Mono:400
https://www.youtube.com/channel/UCXIJgqnII2ZOINSWNOGFThA
https://yt3.googleusercontent.com/G3gLy3HBgiZ21mEt1uzR0VPA6VXpsgJReuD7Z91nHwcgyFVu_QpHNpxuULN1D0YEQBwD0F1HwQ=s900-c-k-c0x00ffffff-no-rj
https://yt3.googleusercontent.com/G3gLy3HBgiZ21mEt1uzR0VPA6VXpsgJReuD7Z91nHwcgyFVu_QpHNpxuULN1D0YEQBwD0F1HwQ=s900-c-k-c0x00ffffff-no-rj
android-app://com.google.android.youtube/http/www.youtube.com/channel/UCXIJgqnII2ZOINSWNOGFThA
ios-app://544007664/vnd.youtube/www.youtube.com/channel/UCXIJgqnII2ZOINSWNOGFThA
https://www.youtube.com/
https://accounts.google.com/ServiceLogin?service=youtube&uilel=3&passive=true&continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26app%3Ddesktop%26hl%3Den%26next%3Dhttps%253A%252F%252Fwww.youtube.com%252F%2540FoxNews%252Fstreams&hl=en&ec=65620
https://www.youtube.com/
https://www.youtube.com/
https://www.youtube.com/feed/subscriptions
https://www.youtube.com/feed/you
https://www.youtube.com/feed/history
https://accounts.google.com/ServiceLogin?service=youtube&uilel=3&passive=true&continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26app%3Ddesktop%26hl%3Den%26next%3Dhttps%253A%252F%252Fwww.youtube.com%252F%2540FoxNews%252Fstreams&hl=en
https://www.youtube.com/feed/trending?bp=6gQJRkVleHBsb3Jl
https://www.youtube.com/channel/UCkYQyvc_i9hXEo4xic9Hh2g
https://www.youtube.com/channel/UC-9-kyTW8ZkZNDHQJ6FgpwQ
https://www.youtube.com/feed/storefront
https://www.youtube.com/channel/UC4R8DWoMoI7CAwX8_LjQHig
https://www.youtube.com/gaming
https://www.youtube.com/channel/UCYfdidRxbB8Qhf0Nx7ioOYw
https://www.youtube.com/channel/UCEgdi0XIXXZ-qJOFPf4JSKw
https://www.youtube.com/feed/courses_destination
https://www.youtube.com/channel/UCrpQ4p1Ql_hG8rKXIKM1MOQ
https://www.youtube.com/podcasts
https://www.youtube.com/playables
https://www.youtube.com/premium
https://tv.youtube.com/?utm_source=youtube_web&utm_medium=ep&utm_campaign=home&ve=34273
https://music.youtube.com/
https://www.youtubekids.com/?source=youtube_web
https://www.youtube.com/account
https://www.youtube.com/reporthistory
https://www.youtube.com/about/
https://www.youtube.com/about/press/
https://www.youtube.com/about/copyright/
https://www.youtube.com/t/contact_us/
https://www.youtube.com/creators/
https://www.youtube.com/ads/
https://developers.google.com/youtube
https://www.youtube.com/t/terms
https://www.youtube.com/t/privacy
https://www.youtube.com/about/policies/
https://www.youtube.com/howyoutubeworks?utm_campaign=ytgen&utm_source=ythp&utm_medium=LeftNav&utm_content=txt&u=https%3A%2F%2Fwww.youtube.com%2Fhowyoutubeworks%3Futm_source%3Dythp%26utm_medium%3DLeftNav%26utm_campaign%3Dytgen
https://www.youtube.com/new
https://tv.youtube.com/learn/nflsundayticket
https://www.youtube.com/
https://www.youtube.com/feed/subscriptions
https://www.youtube.com/feed/you
https://www.youtube.com/feed/history
https://www.youtube.com/redirect?event=channel_header&redir_token=QUFFLUhqbGJPQ1VST3dRNU43LXVodVp6X0dVUXhjTlNFd3xBQ3Jtc0tuaHJKLVhEXzVBTVd5UFY0ZVZORlJjUjg4YmNOckdsSmNBNWxWNnl0czhCdVB6bVFnX0dmNFlNcXBVSXlJT0RXa1c2dTBqSE55d3lVSzB2WmdGQV8zdHN4Y3R1ZnhoNjBMbTRSNmpNWkVobXRkY2VOdw&q=https%3A%2F%2Fwww.facebook.com%2FFoxNews%2F
javascript:void(0);
https://www.youtube.com/watch?v=wqgcfnGhZAQ
https://www.youtube.com/watch?v=wqgcfnGhZAQ
https://www.youtube.com/watch?v=wqgcfnGhZAQ
https://www.youtube.com/watch?v=6QHQNLvLbCw
https://www.youtube.com/watch?v=6QHQNLvLbCw
https://www.youtube.com/watch?v=6QHQNLvLbCw
https://www.youtube.com/watch?v=BK2YxPPRqlg
https://www.youtube.com/watch?v=BK2YxPPRqlg
https://www.youtube.com/watch?v=BK2YxPPRqlg
https://www.youtube.com/watch?v=h-pablVGCi4
https://www.youtube.com/watch?v=h-pablVGCi4
https://www.youtube.com/watch?v=h-pablVGCi4
https://www.youtube.com/watch?v=1GGGtFXkZkY
https://www.youtube.com/watch?v=1GGGtFXkZkY
https://www.youtube.com/watch?v=1GGGtFXkZkY
https://www.youtube.com/watch?v=ZSASa_v1yPA
https://www.youtube.com/watch?v=ZSASa_v1yPA
https://www.youtube.com/watch?v=ZSASa_v1yPA
https://www.youtube.com/watch?v=CNzY3VEdt-I
https://www.youtube.com/watch?v=CNzY3VEdt-I
https://www.youtube.com/watch?v=CNzY3VEdt-I
https://www.youtube.com/watch?v=FozB0WN08PY
https://www.youtube.com/watch?v=FozB0WN08PY
https://www.youtube.com/watch?v=FozB0WN08PY
https://www.youtube.com/watch?v=JmubWbdVO_I
https://www.youtube.com/watch?v=JmubWbdVO_I
https://www.youtube.com/watch?v=JmubWbdVO_I
https://www.youtube.com/watch?v=qimzFSBMtSI
https://www.youtube.com/watch?v=qimzFSBMtSI
https://www.youtube.com/watch?v=qimzFSBMtSI
https://www.youtube.com/watch?v=ynUduYkW7wQ&pp=0gcJCX4JAYcqIYzv
https://www.youtube.com/watch?v=ynUduYkW7wQ&pp=0gcJCX4JAYcqIYzv
https://www.youtube.com/watch?v=ynUduYkW7wQ&pp=0gcJCX4JAYcqIYzv
https://www.youtube.com/watch?v=O10-HH8o63Y
https://www.youtube.com/watch?v=O10-HH8o63Y
https://www.youtube.com/watch?v=O10-HH8o63Y
https://www.youtube.com/watch?v=VbFafFkFALs&pp=0gcJCX4JAYcqIYzv
https://www.youtube.com/watch?v=VbFafFkFALs&pp=0gcJCX4JAYcqIYzv
https://www.youtube.com/watch?v=VbFafFkFALs&pp=0gcJCX4JAYcqIYzv
https://www.youtube.com/watch?v=cB6d0H3mSNA
https://www.youtube.com/watch?v=cB6d0H3mSNA
https://www.youtube.com/watch?v=cB6d0H3mSNA
https://www.youtube.com/watch?v=3CNWgNK9DYc
https://www.youtube.com/watch?v=3CNWgNK9DYc
https://www.youtube.com/watch?v=3CNWgNK9DYc
https://www.youtube.com/watch?v=JOrDQQi-CnA&pp=0gcJCX4JAYcqIYzv
https://www.youtube.com/watch?v=JOrDQQi-CnA&pp=0gcJCX4JAYcqIYzv
https://www.youtube.com/watch?v=JOrDQQi-CnA&pp=0gcJCX4JAYcqIYzv
https://www.youtube.com/watch?v=ablayLrPBP8
https://www.youtube.com/watch?v=ablayLrPBP8
https://www.youtube.com/watch?v=ablayLrPBP8
https://www.youtube.com/watch?v=WWOdkdULIGw
https://www.youtube.com/watch?v=WWOdkdULIGw
https://www.youtube.com/watch?v=WWOdkdULIGw
https://www.youtube.com/watch?v=gJ16WAolAqc
https://www.youtube.com/watch?v=gJ16WAolAqc
https://www.youtube.com/watch?v=gJ16WAolAqc
https://www.youtube.com/watch?v=Lk0Y6V7ulK4
https://www.youtube.com/watch?v=Lk0Y6V7ulK4
https://www.youtube.com/watch?v=Lk0Y6V7ulK4
https://www.youtube.com/watch?v=bReXYMgcX4Q
https://www.youtube.com/watch?v=bReXYMgcX4Q
https://www.youtube.com/watch?v=bReXYMgcX4Q
https://www.youtube.com/watch?v=SSz_82p2U8w
https://www.youtube.com/watch?v=SSz_82p2U8w
https://www.youtube.com/watch?v=SSz_82p2U8w
https://www.youtube.com/watch?v=68OgIApJtbE
https://www.youtube.com/watch?v=68OgIApJtbE
https://www.youtube.com/watch?v=68OgIApJtbE
https://www.youtube.com/watch?v=RMDY-ItWMoU
https://www.youtube.com/watch?v=RMDY-ItWMoU
https://www.youtube.com/watch?v=RMDY-ItWMoU
https://www.youtube.com/watch?v=JqUSpr3BoDg
https://www.youtube.com/watch?v=JqUSpr3BoDg
https://www.youtube.com/watch?v=JqUSpr3BoDg
https://www.youtube.com/watch?v=AzftuRRXb7w
https://www.youtube.com/watch?v=AzftuRRXb7w
https://www.youtube.com/watch?v=AzftuRRXb7w

https://www.youtube.com/watch?v=QTu8lE-s-S8
https://www.youtube.com/watch?v=QTu8lE-s-S8
https://www.youtube.com/watch?v=QTu8lE-s-S8
https://www.youtube.com/watch?v=Yli7RwGoDKU
https://www.youtube.com/watch?v=Yli7RwGoDKU
https://www.youtube.com/watch?v=Yli7RwGoDKU
https://www.youtube.com/s/desktop/70f744c3/cssbin/www-main-desktop-watch-page-skeleton.css

In [12]:
print(element[74].get_attribute('href'))

https://www.youtube.com/watch?v=6QHQNLvLbCw

In [13]:
fxy_url = element[74].get_attribute('href')

In [14]:
print(fxy_url)

https://www.youtube.com/watch?v=6QHQNLvLbCw

In [15]:
#Part 2: Get the youtube video

In [17]:
#https://stackoverflow.com/questions/75794919/how-to-segment-and-transcribe-an-audio-from-a-video-into-timestamped-segments
from pytube.cipher import get_throttling_function_code

def patched_throttling_plan(js: str):
    """Patch throttling plan, from https://github.com/pytube/pytube/issues/1498"""
    raw_code = get_throttling_function_code(js)

    transform_start = r"try{"
    plan_regex = re.compile(transform_start)
    match = plan_regex.search(raw_code)

    #transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
    transform_plan_raw = js

    # Steps are either c[x](c[y]) or c[x](c[y],c[z])
    step_start = r"c\[(\d+)\]\(c\[(\d+)\](,c(\[(\d+)\]))?\)"
    step_regex = re.compile(step_start)
    matches = step_regex.findall(transform_plan_raw)
    transform_steps = []
    for match in matches:
        if match[4] != '':
            transform_steps.append((match[0],match[1],match[4]))
        else:
            transform_steps.append((match[0],match[1]))

    return transform_steps


with mock.patch('pytube.cipher.get_throttling_plan', patched_throttling_plan):
    from pytubefix import YouTube
    from pytubefix.cli import on_progress
    
    url = fxy_url
    
    yt = YouTube(url, on_progress_callback=on_progress)
    print(yt.title)
    
    ys = yt.streams.get_audio_only()
    ys.download("/Users/johncburns/Documents/foxnewstest.mp4")

Attorneys for accused anti-Israel protest ringleader Mahmoud Khalil holds news conference

In [ ]:
#Part 3: Create the transcript

In [11]:
#https://superuser.com/questions/624561/install-ffmpeg-on-os-x
model = whisper.load_model("base")
result = model.transcribe('/Users/johncburns/Documents/foxnewstest.mp4/Attorneys for accused anti-Israel protest ringleader Mahmoud Khalil holds news conference.m4a')
print(result["text"])

/Users/johncburns/anaconda3/lib/python3.11/site-packages/whisper/transcribe.py:126: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")

 And then we'll have some time for questions. And I also wanted to let folks know is housekeeping that a recording of this briefing will be sent to all of their participants afterwards. It might take a little bit to buffer, but it will be coming your way once that's finalized. So with that, I'll go into introductions. The first person we're going to hear from is Mark Vanderhoud. Mark is a practicing attorney and founder of Vanderhoud, LLP. He is representing Mahmoud Khalil and the Immigration Proceedings. Johnny's notice is also is a partner at Vanderhoud LLP. And he is representing Mahmoud and the Immigration Proceedings as well. Hey, Johnny. And Bahra Azami is the legal director of the Center for Constitutional Rights, CCR, who argued in federal court that New Jersey is the proper venue for Mr. Khalil's case to be heard and so much more. And that will be our group today. So with that, Mark, what on I turn over to you to share with us a little bit about the Rubio letter. And what if the Trump administration is or is not achieving its goals right now, and what the impact on this has been to Mahmoud. Mark. Thank you, Ari. And good afternoon, everybody. After a month, really, of hiding the ball in this case, and refusing to produce any evidence to support the charge if they have that Mr. Khalil's presence in the United States is potentially serious adverse foreign policy consequences, which is what the charges in this case. The government submitted, as you all have seen now, a two-page document, two pages. That's it. And in that, Secretary of State Rubio says that Makhmoud's presence here would create adverse foreign policy interests. But what does he talk about? He talks about first amendment activity in the United States and the effect on people in the United States. His determination, quote unquote, has absolutely nothing to do with foreign policy. This vision of law is something that has been rarely used. It's we use, it was supposed to be introduced for the purpose of like saying to the shaver on shouldn't stay in the United States. Really, like public figures like that, it is nothing to do. This law was not to be used to go after people for first amendment protected activity. What the Rubio letter talks about is they're trying to protect they say Jewish students in the United States, Jewish people in the United States, from epitomeantism. But what is the anti-semitism? It is criticizing Israel and the United States for the slaughtering that is going on in Gaza and in Palestine. That's what this case is about. And that's what this case is really centered on. The rights of people in this country, citizens and immigrants alike who are all protected by the Constitution, by the first amendment to be able to speak out. Whatever their views may be, popular or not, that's what this country is about. Yet this administration wants to silence, like mood, wants to silence people speaking out against the government of Israel or government of United States. And where would this lead? Are we going to now throw people in jail for speaking out against the Social Security cuts in this country? This is a dangerous slope. And we are taking a stand, they have a McMood and he is taking a stand, he's decided to stay in jail and fight this case to the bitter end. While we try to establish that people like McMood have a constitutional right to speak out in this country and they should not be, the government should not be using this really bogus statute, saying it's against Jewish foreign policy interests. Let me pass this on to Johnny now, I guess, to talk about what's going to go on in immigration court. Thanks, Mark. And I just wanted to jump in very quickly before I handed over to Johnny, sorry, Johnny, to say exactly what Aaron just did in the chat. If you have questions for Q&A section, please drop them in the chat. And we will get to as many of them as we can. Please note who you are and what outlet you're coming from when you put in your question. And with that, I will now pass along to Johnny. Thanks a lot. And thanks, Mark, for setting that up. Tomorrow in immigration hearing, worst in immigration court, we're set for a hearing where the government will attempt to establish that it's met its burden to show that it can deport McMood for lawful conduct, conduct that's protected by the free speech clause of the first amendment. Now, the immigration judge has already put on the record during our last hearing that we are not in fact in federal court tomorrow. And that's a nod to the government's position that immigration judges can't rule on the constitutionality of immigration laws. But in order to comply with due process and ensure that McMood's right to a full and fair hearing is fulfilled, tomorrow should be a full blown evidentiary hearing and not just a rubber stamp on the government's baseless belief that it can take away McMood's green card and separate him from his pregnant US citizen wife and their soon to be born US citizen child. Now, the immigration judge has also told us that tomorrow she will make a finding as to whether McMood is removable. But we are far from the end of the road if that happens. If the immigration judge determines that he is in fact removable for lawful conduct that is protected by the first amendment of our constitution, the case will move on to what's called the relief stage of removal proceedings where McMood and our legal team will be able to litigate his right to remain in the United States, even though the immigration judge has found him deportable. This process plays out in immigration court and it will most certainly require several more hearings before final decision can be made in the immigration case. But regardless of that fact, I think the bigger picture here that we all need to keep focus on is that tomorrow's hearing has momentous implications. Whether the government can act in violation of the constitution to deport someone is front and center and our position is that it cannot. And now we'll move on to Bob Herd to talk about where we're at in the district court proceedings and what this means moving forward. Hi, everyone. So as you all know, and the attention I've been placed earlier, we have a case in federal court in New Jersey, that is ongoing and active. And just as the government was trying to manipulate jurisdictional rules to keep McMood out of that New York federal courts in New York and New Jersey and into the federal circuit in Louisiana where the law is very favorable to the government, they are also now attempting to leverage the considerable power and authority and the limited protections that are available in immigration court and to argue that in immigration court as opposed to in federal court, the court has to largely accept what the Secretary of State has said about McMood and largely defer to the executive's conclusions about the fact that he is a threat to foreign policy, simply because the Secretary of State says without analysis or evidence that he deems McMood a threat to national security. This is a sort of a tacky Soviet style Dictat that's like equal parts empty and chilling. So we're going to fight name immigration court, as Mark and Johnny has said, but the reason we have a habeas corpus petition in federal courts is that federal courts have a robust obligation to enforce the constitution and enforcing the constitution means, of course, recognizing and enforcing the constitutional rights that are so centrally at stake in this case, but it also means in a federal court and in our system of separation of powers, we don't have to accept the leader's say so as the final word. The law requires a federal court to question this determination and ensure that the determination is consistent with basic constitutional protections in the First Amendment and also in due process, we've talked a lot about what the First Amendment requires and as journalists, you are all very familiar with it, but there's another fundamental principle here that the government can't just operate on hidden law based on one executive officials say so. Does anyone here know what conduct they would have to engage in that would trigger an adverse foreign policy interests to the United States? No one does, no one can, which is what's so dangerous about this law and why the federal court case has to proceed in parallel. I really appreciate it. I am now going to start going through some questions. I see a bunch in the Q&A functions, so keep them coming and we will go through them, go through them and try to get to as many as we can. We also have some other folks from the broader co-counsel team on this briefing. So you might see Baja Arjani or Mark bringing them in as necessary depending on their expertise. So I am first going to start with a question from Gregory at AFP, Elements of it. I've also seen from questions from others. But the question is, what is the chance that Mahmoud will be released tomorrow and how is Mr. Khalil's state of mind right now? The question also gets into some questions about just the logistics of the hearing tomorrow. So if whoever is answering could talk about, when, where, how, as well in answering that, that would be great. Sure, I'll start. So the hearing is a hearing that's physically taken place in Jenna, Louisiana, where they ship Mahmoud to in the middle of the night, the night he was arrested. And that's where he is detained. And that's what the government has been doing in a lot of these cases, sending people down to remote locations away from the families, away from their legal support. And that's where the hearing is taken place. It, the lawyers will be in various places, including them remotely. But the hearing will be conducted. We had asked that we have sufficient time to review the government's evidence. And I'm respond to it. It was only submitted at five o'clock yesterday. The judge denied a request to do that. And she scheduled the hearing for Friday morning. Or Friday, I guess afternoon in Louisiana, one o'clock. So at that hearing, we will be contesting the evidence. We'll be asking in advance to depose us, Secretary of State, Marco Rubio. We will be asking the government to have to meet its burden. Rubio's letter has nothing to do as I stated with foreign policy. And we'll be challenging that in court. I'm thinking whether the, what the judge will do with that is yet to be seen. And although she did say when I raised that on Tuesday in the hearing and said we'd be doing that, her response was something the effective. Mr. Vanderhock, we're not a federal court here. There's a court of limited jurisdiction. And she didn't say she would deny it, but she certainly did not seem open to it. But we'll see where that goes because we have to, we have the right. Mr. Colliel has the right under two process to confront the evidence against them. And that's what we want to examine. Secretary of State, Rubio about. Yeah, and I'll briefly speak to how Mark Mood is feeling. You know, we've been in continuous communication with him. He's feeling confident. He's feeling strong and he's feeling supported by the community. And he understands that he has done nothing wrong. He has only engaged in lawful conduct. And his wife and his family are sources of support for him. And the support that he's received, not only nationally, but internationally from people who are appalled by what the US government is trying to do in this case is giving him the ability to move forward, knowing that the correct outcome will be achieved, whether it's tomorrow or in the future. Yeah, and I would just add one thing on that in terms of the essence of this case and that it is really a challenge to everybody in this country's First Amendment rights. The statute itself, when Congress enacted this, the authors of the statute in Congress was very concerned about whether this would be used against immigrants in this country in violation of what would be activity protected by the First Amendment if there were US citizens. And US citizens and permanent citizens' country have the exact same constitutional rights that these would be the First Amendment. So Congress put it into provision saying it cannot be used against individuals for activity that would be protected by the First Amendment if engaged in by US citizens, unless there is a compelling government interest based on foreign policy. And Secretary St. Rubio has articulated zero in that regard and that's what we'll be asking the judge to review because she has the right to review whether there's serious grounds to support the accusation in this case. Thank you, boss. I'm now going to move on to a question from Gloria Cosmino at CNN. Please talk more about the evidence that was submitted by the government. Is the Rubio letter the only thing? And if so, what does that tell you? So they have submitted, this is the only, the Rubio letter is the only piece of evidence going to the main charge in this case that is President of the United States could have potentially serious foreign policy consequences. There is zero else. They've submitted a bunch of other paper work on these bogus charges they added later on about alleged misrepresentations on applications and things that he's been involved in in negotiations that he was involved in in that Columbia with the administration and the protesters. But it is zero to do with the foreign policy charge and there is zero support for the government's allegations about any misrepresentation. We'll be dealing with that in court tomorrow. So when we get to that, but there's no there there at all. So you're not concerned with that at all. Thanks, Mark. The next question is from Reuters and it's regarding bond. The question is, have you or will you file for an immigration bond? And if Judge Comin's terminates the case with or without prejudice, is that appealable in your view to the BIA? And this came from Jonathan Allen. So in immigration court, it's the government's position that if a non-citizen falls within this foreign policy ground that Mark has been talking about, they are ineligible for bond and immigration judge can't even consider whether to re-determine the custody of that non-citizen. And so as of right now, the government seems to believe that the immigration judges constrained by this regulation. The regulation is violentive of the immigration laws. It's certainly in violation of the constitution and that's why in you know, in habeas proceedings, one of the pending motions is bail from Mark Mood because the immigration framework, as it's set up currently, doesn't actually ensure that his right to have his custody re-determined is fulfilled. So this regulation essentially counters our understanding of how custody is supposed to work in the civil context. There's really only two reasons a non-citizen can be detained, either because they're a flight risk or a danger. But the government's position is that that's all irrelevant. So long as you know, there's an assertion that they're subject to the foreign policy ground, which is straight up unconstitutional. And again, that's being challenged in the habeas proceedings. Thanks, Johnny. The next question is from WNYC. Based on the judge's prior statements, has she given any indication of how she plans to rule in Mark Mood's case? She has not. She hasn't seen any evidence, but given her statement in court on Tuesday that, didn't seem to be willing to look very favorably on a request to Sapina Secretary of State, Ruby Oubio to say, what's the story here? Where's your evidence? We hope she will change her mind and hope she'll understand that that has to be done. But we really have no idea. We are hopeful that she will agree. There's no evidence and there's no evidence to she terminate the case. And you should be released. But whether she'll do that, we'll see tomorrow or beyond, depending on if we actually finished tomorrow. But maybe I thought maybe, but her you may want to sort of add on about the bill issue perhaps. And what we're going to do with the federal court. Yeah, there's some questions in the chat about what's left to decide in the federal court. And one of the urgent motions we have before the court and that we've repeatedly asked the federal judge to address is one, a motion for bail that would have the federal court order Mahmoud released from custody and also a motion to, and that would be, I think, the most important relief, alternatively and in a minimum, a motion to transfer him back to the jurisdiction of the court, which would certainly not ideally have him confine Elizabeth, but at least in a place where he could regularly meet in person with his lawyers and most importantly, with his, with nor his wife. And then more broadly, we are seeking to have the, the federal court rule that the application of this provision to Mahmoud and even more broadly would be on constitution. So we hope the court reaches the bill motion soon. He knows we're eager to have it heard. Thank you, both. Relatedly, I think we covered a little bit of this, but when I make space for if there's anything others want to add. Stephanie Apalma from the Financial Times has asked, you talk about what would happen if the judge finds Mahmoud is removable. Could you talk about what would happen if she finds the evidence does not support his removal? Additionally, and I think we covered this a little bit, but by her, if you have more to add, please do. How would you potential outcomes in immigration court then impact proceedings in federal court? So just very briefly on the immigration aspect of it. If she were to find the government hasn't met its burden approving by clear convincing and unequivocal evidence that he is deportable, she has to terminate the proceedings and he would be released. Now the government would have the right to appeal, but we would be immediately arguing for his release and we would expect that to happen. The other part of the question is, what happens in his federal case if he is deemed not removable? Yeah, slightly more general than that. So how would you potential outcomes in immigration court then impact proceedings in federal court? Well, very importantly, the habeas court was proceeding in federal court is independent of the immigration proceedings because anytime someone is in custody of the executive branch and that custody is unlawful, even if the executive branch and the immigration courts are unwilling to make that determination. The federal court always has the power and the obligation to decide the legality of the detention and order the person released if they are, if the court determines their unlawfully detained, which we obviously think is self-evident. So we're moving on on both fronts and recognizing that we have the most powerful arguments and the most powerful audience in federal court. Thanks. I'll try to get in two more and then I think folks have to jump. So again, thank you all and I'm sorry we didn't get to your question but we are trying to cover as much ground as possible and combine themes. The next question is from Tanvi Misera. Her, their question is, I understand it is the government's burden at this point to prove that Mr. Khalil is deportable and immigration court. Do you think they have met that burden with this memo? There were also some questions in the chat about what that burden is in immigration court so if folks could answer that as well. I'll pause there for answers to that and then I can ask the rest of the question. So, yeah, sure. The government's burden, they have to meet what's called a clear convincing and unequivocal evidentiary standard. So it's very high. We think that they fallen well short of meeting their burden. As Mark has said several times and many people may have read, the Rubio memo is completely devoid of any factual recitation as to why exactly Mark Moody's presence in the United State

In [18]:
results_text = result["text"]

In [19]:
#Remove stop words:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('stopwords')
nltk.download('punkt')

stop_words = set(stopwords.words('english'))

word_tokens = word_tokenize(results_text)

filtered_sentence = [w for w in word_tokens if not w.lower() in stop_words]

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/johncburns/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/johncburns/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [21]:
type(filtered_sentence)

list

In [25]:
values = pd.value_counts(np.array(filtered_sentence))

In [28]:
#Immigration, trans, athelete, black, white, vaccines, Palestine, Israel
values["immigration"]

34

In [47]:
pd.set_option('display.max_rows', 500)
values = pd.value_counts(np.array(filtered_sentence))

In [50]:
type(values)

pandas.core.series.Series

In [54]:
df = values.to_frame()
df.head(100)

                  0
.               222
,               208
's               88
court            43
immigration      34
case             29
government       29
would            24
?                23
federal          23
question         20
evidence         19
judge            17
'll              17
Mark             16
n't              16
policy           15
hearing          15
're              14
Rubio            14
foreign          14
tomorrow         14
also             13
right            13
think            13
people           13
one              13
going            12
States           12
United           12
support          10
McMood           10
Secretary        10
burden           10
Mahmoud           9
proceedings       9
Johnny            9
whether           9
US                9
first             9
country           9
Mr.               8
determination     8
see               8
State             8
us                8
know              8
'm                8
say               8
really            8
letter            7
questions         7
submitted         7
Khalil            7
talk              7
Amendment         6
've               6
said              6
law               6
protected         6
constitution      6
custody           6
First             6
even              6
like              6
courts            5
nothing           5
seen              5
certainly         5
amendment         5
make              5
process           5
trying            5
rule              5
position          5
conduct           5
rights            5
citizens          5
get               5
Thanks            5
constitutional    5
executive         5
end               5
asked             5
folks             5
released          5
New               5
add               5
place             5
go                5
Thank             5
habeas            5
well              4
move              4
meet              4
feeling           4
used              4
want              4
Yeah              4
person            4

In [ ]:
###################

In [ ]:
#Second video
#https://www.youtube.com/watch?v=q3WRLEgG_8w

In [56]:
fxy_url2 = "https://www.youtube.com/watch?v=q3WRLEgG_8w"

In [58]:
from pytube.cipher import get_throttling_function_code

def patched_throttling_plan(js: str):
    """Patch throttling plan, from https://github.com/pytube/pytube/issues/1498"""
    raw_code = get_throttling_function_code(js)

    transform_start = r"try{"
    plan_regex = re.compile(transform_start)
    match = plan_regex.search(raw_code)

    #transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
    transform_plan_raw = js

    # Steps are either c[x](c[y]) or c[x](c[y],c[z])
    step_start = r"c\[(\d+)\]\(c\[(\d+)\](,c(\[(\d+)\]))?\)"
    step_regex = re.compile(step_start)
    matches = step_regex.findall(transform_plan_raw)
    transform_steps = []
    for match in matches:
        if match[4] != '':
            transform_steps.append((match[0],match[1],match[4]))
        else:
            transform_steps.append((match[0],match[1]))

    return transform_steps


with mock.patch('pytube.cipher.get_throttling_plan', patched_throttling_plan):
    from pytubefix import YouTube
    from pytubefix.cli import on_progress
    
    url = fxy_url2
    
    yt = YouTube(url, on_progress_callback=on_progress)
    print(yt.title)
    
    ys = yt.streams.get_audio_only()
    ys.download("/Users/johncburns/Documents/foxnewstest.mp4")

LIVE: Markets uneasy on Trump’s ‘Liberation Day’ tariffs | Brian Kilmeade Show

In [59]:
#https://superuser.com/questions/624561/install-ffmpeg-on-os-x
model = whisper.load_model("base")
result = model.transcribe('/Users/johncburns/Documents/foxnewstest.mp4/LIVE: Markets uneasy on Trump’s ‘Liberation Day’ tariffs | Brian Kilmeade Show.m4a')
print(result["text"])

/Users/johncburns/anaconda3/lib/python3.11/site-packages/whisper/transcribe.py:126: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")

 you you you you you you you those schools used to have to create having hammered because most people simply invest in the indexes and the indexes are down significantly. So I think the president is banking on the idea that people trust, that this is why he was elected. Yep. The people trust his economic instincts. But you know, that only goes so far. I mean, at some point the proof is in the pudding, as they say. And he's going to have to, I think, produce results. And that includes on Wall Street. Bruce Kevin Hassett is economics adviser cut to. Well, President Trump is going to decide how many countries. The point about 15 countries is that we have massive, massive trade deficits with about 15 countries. It doesn't mean that there aren't a lot of other unfair trade practices around the world. And so the reciprocal part of our trade actions will be visible to everybody on the second. The thing I can say is if you look at what we've already accomplished, I don't think there's ever been a trade team that's more united and accomplished in the president's goals. If you think about it, there are a bit action after action after action. And you mentioned the auto tariffs since they were the past that's easier for me to talk about. The auto tariffs coming from a backstory that I think is really interesting, Maria, that has really haunted all of us who studied the U.S. economy. So right now on the economy, according to CBS, he's getting 44% approval on inflation 56 disapproval on the economy, 48.52 is usually much inverse on that. When asked about tariffs, not enough people say only 7% thinks he's not doing enough on tariffs. Right amount, only 31% says he's doing the right amount, too much 55%. So so far it's been all rocking the economy and anticipation of what it will do. But you know his overall objective, Michael, is to bring manufacturing back and to give America control of their own economy again. And do you think it's possible? That's a question that only time will tell I think. Well, look, I mean he has had some successes with investment in America from companies that could have invested elsewhere. And I think he would argue, as with Kevin Hasick, that the reason they are investing here, rather than Asia or Europe, is to avoid the tariffs. That look everybody wants access to American consumers because American consumers are not only numerous, they are the wealthiest in the world by and large. And so to get access to the American market, these companies would rather be based here, have their manufacturing here. As many of the automakers discovered years and years ago, it was better to build Mercedes and Alabama than it was to build them in Germany and ship them to Alabama. And I think the president is banking on that and there's some reason why that is an important part of this. But the other part of it that is that inflation or a tariff can cause inflation because the product simply costs more now and somebody's got to pay that. And if there's enough of that in the society, then you've got the inflation problem again. So I don't think the president has as much time as he thinks he does on this. The public by and large trusted him more than the Democrats on the economy, but that trust can easily evaporate if something goes wrong here. So if I were him, I wouldn't be so patient. I understand. I think it's going to happen massive rebalancing with somewhat friendly countries like Canada, India, Mexico, Brazil, who can be friendly when they want to be. So I think there's going to be people, okay, let me address that. Let me address that. And I think you're going to see a reconfiguring. But what the president's doing is what Joe Biden said he was going to do. He was going to bring pharmaceuticals back to America. That wasn't going to happen. Remember after PPE, we didn't make any. We're using plastic bags. So that's one of his goals too. So we'll see what happens. I know a lot of the unions appreciate it, but I want to talk about what you wrote about over the weekend. Katrina Armstrong resigns as Columbia's interim president after she cuts the deal on Friday, last Friday, saying she'll agree to all nine of Trump administration's demands to change Columbia. And on Saturday, she gets on a conference call and base because it died. Don't worry about what I said. Now Claire Shipman, the ex anchor, takes over. But this weekend Columbia actually had alumni day and they took that time. Many of them to burn their diplomas because of the rest of Makmu Khalil, who's got solid ties to Hamas. What are they thinking? Well, Brian, I think we're going to ask that question of so many colleges around the country. You know, toughs had a woman who was arrested. You've seen them popping up everywhere. Harvard just ended two departments or removed the people in charge of two departments about Middle East faculty. So this is happening everywhere. And I think what's so surprising about it is that Joe Biden did nothing about it. Right? So you have all of these demonstrations last year, all of these anti-Israel pro-Hamas, pro-Palestinian, give me a break. It's pro-Hamas. I mean, this is the media. The New York Times had a story yesterday in which it said that some people, some people believe that the chance to the river, to the sea, Palestine will be free, that that chance talks about the elimination of Israel. It's not some people. That's the entire purpose of the chance is to eliminate Israel, to picture a mid-east without an Israeli state. And so this notion that somehow these people are just engaging in first amendment rights that they're just leading to discussions, below these. They were doing these takeovers of these schools. They were disrupting. They were threatening. And so if you're an Israeli, imagine you're walking by, or even just an American Jewish student, you're walking by a protest and they're saying from the river to the sea, Palestine will be free. That means the end of Israel. And if it isn't the job of the university administrators to protect those students from the harassment and the intimidation and the hate speech that that is, then what is the job of the university administrator? And they have all failed. Columbia has failed. Harvard has failed. Penn has failed. Tufts, you go up and down the line. Virtually every elite college has failed in this regard. And I think the president is hitting back in the only with the only power he has. They're going to investigate the schools. But I love it. Clean up their acts. Absolutely. I don't know if you saw my show on Sunday night. And the thing is, it's not speculation anymore. We know that in the tunnels in Biting Hill hostage, a specific hostage came out and said they told me exactly they have direct links to this. Austin will be free, these organizations in America. And we're bragging about winning the PR war. Mark Goldfelder, a fatter, is representing eight Hamas hostage families, cut 59. Students for justice in Palestine and within our lifetime, which are two of the groups that we just sued in the Southern District of New York. Here by the way is a thank you letter they got afterwards in the PFLP. Another Hamas affiliated terrorist organization thanking them for their service to Hamas. And the beautiful part is when you hire these useful idiots to be your PR agents on American campuses, what you get are useful idiots who make useful idiot mistakes. So for example, here is an actual recruitment flyer for Hamas that they handed out on campus. And it reads this is an intentional and coordinated effort to uphold the principles of Hamas, the PFLP and the Al-Axam order. Where did that appear? September 24th, 2024 on Columbia's campus handed it out by the CUAD, the group that Mahmoud Khalil represents. Please. This is what Marco Rubio just got to present, done finished through. Anybody with this guy's got to go. That's Khalil, these groups, since when are we allowing Hamas to have a say in what happens on our college campuses? Is this crazy? And Brian, that gets to the heart of America's interest here. We have labeled these groups terrorist organizations. And that comes certain penalties. And those penalties can be applied to the individuals espousing that ideology representing those and spreading and spreading the tenants of those organizations. That's what Donald Trump is forcing the college to do. And they deserve to be penalized if they won't do it. You think it's Michael, he's doing everything at once. It's almost overwhelming like to prepare for a show. He's handled the primary schools with decentralizing. Okay, got it. And then on the most high class expensive schools in the country, we are going to have zero tolerance to the anti-Semitic behavior at once. And it's going to cost you $400 million to straighten out. Hey, University of Pennsylvania, you allowing a Transmento, competing sports would take him back $175 million. I mean, usually this is one of these stories a year. And then you start scooping up 300 anti-American, ungrateful college students, getting put him on the launch pad to be deported. That's massive action. That's a message. Absolutely. And look, I agree with you, Brian. It is, it's hard to keep up even, right? Even for journalists, it's very hard to keep pace with its president and all of these orders. And I think he's paying something of a price for that. I think there is a sense of overwhelmingness in terms of the system can't process all of these ideas. Nonetheless, they are all essential. This is big time stuff. The whole thing with Doge. You know, I wrote about this too, that you cannot make this argument about what Doge is doing if you forget that of our $7 trillion budget, approximately $2 trillion of it is borrowed. And so there when you want to give money away, whether it's through transgender folk shows and Ecuador or whatever it is, you've got to balance it against the fact that 130% or more of that money is borrowed. Yes. That's what's infuriating that so much of the government has just taken it for granted. The money will always be there. We'll just borrow more when we run out. We've run out of room to live that way. And that's why I think it's so important what the president is doing. But unfortunately, the argument is being consumed by just these headlines about this and that and every other thing. It's quite a remarkable achievement what he's doing. He's not going to get enough credit for it because one thing overshadows another. Maybe if people go to Fox Nation, we're at the number one network. It's a streaming service that we have that everyone knows about. It has Brett Bares, seven, you know, it's an hour long. He meets with seven members of Doge and Musk is in the middle. And they all talk separately about what they're doing to straighten out the government. They're not saying people are bad. In fact, they say nice things about the career service members who are welcoming Doge. Help me get a voice here. Help me fix this job. We matter suddenly. You know, it's not an abyss. So, I think that people will come away from that is just the chaos in the federal government. The fact that computer systems don't talk to each other. So one agency has 27 chief information officers. Yes, just to make sense of each. H.S. I mean, it's crazy. It's just crazy. Well, Michael can continue writing. Stay on top of the Columbia thing because as we buzz you write, we know we're going to get a new president of Columbia very shortly because she's not Claire Shipman who hates Trump, who's way to the left is not going to last either. Michael, thank you. So with us right now is Senator Dave McCormick. You know, normally it's always great to have mom, but especially today because you have a brand new book out tomorrow, officially, but you can get it now. Who believed in you? How purposeful mentorship changes the world. Congratulations, Senator. Hey, Brian, good to be with you. So you thought about you had this book going before the pandemic. Yeah, well, it started during the pandemic. You know, we were locked up with our six daughters and they couldn't see their teachers or their coaches. We started to think about, you know, their relationships were strained. We started to think about Dean and I how mentorship had changed our lives and that they were had a real gap. And we started to talk to some of our friends about it, you know, successful folks and across the board, all of them had been benefited by a mentor to that had helped them become who they are, whether it's Sarah, how could be Sanders or Satin Adele or Steve Schwartzman or, you know, Brian Grazer, the Oscar winning producer. So we said, you know, let's do this project where we talk people and ultimately became a book. And so the book is about mentorship and it's about the, not the people you've ever heard of. It's not about the famous people. It's about the people who helped them become who they are. And the key thing here is who believed in you, right? Have you gone to the people who believed in you, Brian and said, thank you because the people we interviewed said, man, we wish we had done that. And then what are you doing to pay it forward? Because all of us can make a huge difference if we help young people become their best selves and they change the world. Right. And for you, a lot of sports, you're a great athlete. You play football, you wrestled all the way through college, went to West Point, became a very, I have to serving in the military, became very successful in business and then said, hey, you know what? I'm going to try this political thing. Almost you and Dr. Oz went down to a death march in the primary and then this huge win over a long time sitting center, center, Casey in Pennsylvania. So the sitting center has just been doing this for two months now. Right. So the person who you cite is a football coach. Yeah, the football coach. You know, I was, I was riding the bench. I was a sophomore in high school and the coach got fired and a new coach came in and he watched all the films and he came to me that the summer before my junior year and said, I think you got real potential here. You're going to have to earn it. So I go into the football training camp. At the end of the camp, he makes me the co-captain as a junior. Wouldn't have ever imagined it. I ended up having a, you know, a great season and other great season. I've become an all-state football player. I get recruited to West Point. I ultimately wrestled a West Point not football, but, but I got recruited. It changed my life. I'm not kidding you, Brian. I never thought of myself as that guy. I never thought I was the captain of the team. I didn't think I was that good. He saw something in me. I didn't see him myself and it literally changed the course of my life and there's been a couple people like that. Right. And so how many people do you interview in their book? We interviewed about 25 key people in our books. People in political life, people in business, people that were actors. I mean, it's our Hollywood producers, David Chang, the famous chef and the stories are incredible. And may I share one or two? Sure. Just to give you an example. A great example is Satin Adela. So he's the CEO of Microsoft. I think arguably the most successful CEO in the world right now. And he tells this story about he grew up in India and had a cricket coach that really helped him find himself. But he joined Microsoft eventually as a software developer. It was sort of promoted to mid-level management. And this guy, Microsoft buys this software company called Great Plains Software. And the guy who started it becomes Satya's boss and runs all the software businesses in Microsoft and sees his promise in Satya mentors and helps him become, gets to know his parents, really becomes his person. And that guy's name was Doug Bergam, who went on to become the governor and now President Trump, Secretary of Energy. And when they were looking for a CEO for Microsoft, Satya was not sort of in the group that was most likely. He was a consideration. They called Doug Bergam and said, well, you know, what do you think? Satya said he's incredible. He's the guy to lead Microsoft into the future. And of course, that's what's happened. So these relationships come and go and it makes all the difference in the world. The other thing we saw is mentors, you know, they have trust trusting relationships. They have common values. They have commitment to one another. But the thing they do that is absolutely necessary. They help you have the confidence to overcome failure. They help you have the confidence to take risk. Everybody in this book, they're all these super successful people. They've all failed. We've all failed. I failed. I lost a campaign. So these things happen. And when you face that, that failure, when you face that challenge, mentors can be there to help you dust yourself off and get back in the game. Also when you fail to, you get hardened. You get a lot of, hey, survived it. A bounce back. Okay. So what's the worst come to us? I lose this job. I'll get another. Exactly. You know, I'll find a way. But until you do that and until you break the glass, you don't know. That's right. And that's a lot of time when it comes to parenting, you want to make sure your kids don't feel that. But probably the best thing they could do, it really is feel that right. Nothing's them up. That's no doubt about it. You need resilience. Did you worry about that with your kids being that you was so financially successful? You could do a lot of things that you weren't able to do as a kid. Do you worry about your kids not being tough enough for resilient enough? You know, we, I think we've had good success with that with our kids because we never, did you have to be cognizant of it? Absolutely. Very aware of it. They had to, you know, the best, the best meritocracy you can find is sports. And when your kids play sports, you know, it doesn't matter what happens. How much you want them to succeed? They've got to succeed on their own. So all of our kids for the most part played sports and we try to make sure they earn their way and find mentors. So all my kids and various ways have had mentors. My one daughter now is in particular, sort of has a mentorship with someone who's helping her pursue her career. These things make all the difference. We hope that their success was having great mentors as we've been. So I want to go back to the book, but let's talk about what's happening today. On Wednesday, they call it liberation day. We're going to have reciprocal tariffs with everyone. I mean, things is really unbalanced like India, 40% tariff on cars coming into India. How's that going to happen? You know, some of the imbalances with lumber and Canada, but it's all happening at once. Here's what Donald Trump said last night. The audio's not great, but he said on Air Force One, cut one. The tariffs will be far more generous than those countries were to us. Meaning they will be kinder than those countries were to the United States of America. So how do you see it? I mean, you do have your years of bridge water. This is what you were doing. You're very tapped into the international business. Yeah. Well, first, I try to start with, you know, anxiety and uncertainty is the worst thing you want as a business person. You don't want uncertainty. You want as much certainty as possible so you can make your bets. And the reason the markets are so royal right now is that there's uncertainty. But when I talk to CEOs, I try to say, let's start with the certainty. There's uncertainty. Let's start with the certainty. The certainty is the biggest deregulation in 50 years. The certainty is unlocking energy and energy domes. The certainty is $2 trillion of new investment in the United States. And the certainty is we're going to get the tax cut extensions made permanent, or it's certainly extended. Those are huge s

In [60]:
results_text2 = result["text"]

In [61]:
#Remove stop words:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('stopwords')
nltk.download('punkt')

stop_words = set(stopwords.words('english'))

word_tokens2 = word_tokenize(results_text2)

filtered_sentence2 = [w for w in word_tokens2 if not w.lower() in stop_words]

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/johncburns/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/johncburns/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [64]:
values = pd.value_counts(np.array(filtered_sentence2))

In [66]:
df = values.to_frame()
df.head(150)

                 0
.              675
,              584
's             211
know            79
're             70
n't             66
?               64
going           63
people          55
think           55
tariffs         34
right           32
get             30
said            30
make            28
want            28
go              28
mean            27
got             24
Trump           23
back            22
one             21
see             21
like            20
would           19
thing           19
say             19
much            18
lot             18
Well            18
could           18
president       18
way             15
economy         15
've             15
$               14
bring           14
%               14
Yeah            14
trade           14
time            14
things          13
book            13
guy             13
saying          13
start           13
America         12
us              12
comes           11
'll             11
point           11
great           11
American        11
talk            11
good            11
look            11
Right           10
Brian           10
really          10
countries       10
part            10
'm              10
world           10
companies        9
government       9
talking          9
last             9
years            9
two              9
help             9
markets          9
Biden            8
failed           8
kids             8
take             8
trillion         8
also             8
coming           8
work             8
fact             8
let              8
inflation        7
Donald           7
college          7
certainty        7
question         7
free             7
stuff            7
ca               7
tell             7
making           7
come             7
market           7
Hamas            7
everybody        7
best             7
person           7
President        7
become           7
Columbia         7
jobs             7
cut              7
sure             7
manufacturing    7
Senator          7
something        7
gets             6
Joe              6
job              6
came             6
change           6
saw              6
country          6
better           6
trying           6
give             6
uncertainty      6
wants            6
year             6
massive          6
probably         6
enough           6
new              6
Microsoft        6
well             6
started          6
successful       6
mentors          6
military         6
football         6
never            6
around           6
try              6
many             6
relationships    5
coach            5
workers          5
India            5
remember         5
six              5
little           5
business         5
hey              5
difference       5
serve            5
happens          5
actually         5
waste            5
friends          5
cars             5

In [68]:
df.to_csv('/Users/johncburns/Documents/foxnewstest.mp4/Market3_31_25.csv', index=True)